spring:
  application:
    name: notification-service
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earlier
      key-derializer: org.apache.kafka.commom.serialization.StringDerializer
      value-derializer: org.springframework.kafka.support.serializer.JsonDerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ecommerce.kafka.order.OrderConfirmation, paymentConfirmation:com.ecommerce.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: testUser
    password: passwordUser
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040