version: '3.8'
services:
  mysql:
    container_name: ms_mysql
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - microservices-net
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ms_phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - 8080:80
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: ms_mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo:/data
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: ms_mongo_express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    restart: unless-stopped

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  microservices-net:
    driver: bridge

volumes:
  mysql:
  phpmyadmin:
  mongo:
